-- Becc-bucket personalization hooks for CarterCo's own outbound.
-- The hook generator (enrich-buckets edge fn) writes a personalized DM body
-- (the connected observation + a bridge into the video) per accepted CarterCo
-- lead, drawn floor-up from the prospect's own LinkedIn posts (Bucket 1/2) or
-- their role (Bucket 3). sendspark-webhook bakes personalized_hook into
-- rendered_message at render-ready (appending the link); the /outreach approval
-- card shows hook_bucket + hook_trace as context (the body itself is editable
-- via the existing rendered_message textarea — binding-approved-text).

alter table public.outreach_pipeline
  add column if not exists personalized_hook text,        -- the DM body: observation + bridge into the video (no greeting, no link)
  add column if not exists hook_bucket        text,        -- "1" | "2" | "3" (Becc bucket that won)
  add column if not exists hook_trace         text,        -- one-line reasoning for the operator
  add column if not exists hook_lang          text,        -- "da" | "en"
  add column if not exists hook_generated_at  timestamptz;

comment on column public.outreach_pipeline.personalized_hook is
  'Becc-bucket personalized DM body (observation + bridge into the video; no greeting, no link) for the video DM. Generated by enrich-buckets on CarterCo accept; baked into rendered_message at render-ready (link appended). Null = use the static Bucket-6 website fallback.';

-- Sequential-waterfall state (added when the one-shot generator became the
-- bucket-by-bucket cascade). Lets a floored lead resume deeper on a later touch.
alter table public.outreach_pipeline
  add column if not exists hook_buckets_tried text;

-- Two-layer evaluator reasoning (added when the cascade became evaluator+writer:
-- scrape all sources -> evaluator picks the single best angle with a "why" ->
-- writer writes the body). hook_context holds the chosen-angle age + why, shown
-- in /outreach so the operator sees WHY this angle before render.
alter table public.outreach_pipeline
  add column if not exists hook_context text;

comment on column public.outreach_pipeline.hook_context is
  'Two-layer evaluator reasoning for the chosen hook angle (age tag + why this angle beat the others). Surfaced in /outreach for operator review before render.';
